{{- if default "" .Values.minecraftServer.dynmap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "minecraft.fullname" . }}-dynmap"
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minecraftServer.dynmap.serviceType }}
  ports:
  - name: dynmap
    port: {{ .Values.minecraftServer.dynmap.port }}
    {{- if .Values.minecraftServer.dynmap.nodePort }}
    nodePort: {{ .Values.minecraftServer.dynmap.nodePort }}
    {{- end }}
    targetPort: dynmap
    protocol: TCP
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
{{- end }}
