apiVersion: v1
kind: Service
metadata:
  name: {{ template "minecraft.fullname" . }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minecraftServer.serviceType }}
  ports:
  - name: minecraft
    port: 25565
    {{- if .Values.minecraftServer.nodePort }}
    nodePort: {{ .Values.minecraftServer.nodePort }}
    {{- end }}
    targetPort: minecraft
    protocol: TCP
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
