{{- if default "" .Values.minecraftServer.rcon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "minecraft.fullname" . }}-rcon"
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minecraftServer.rcon.serviceType }}
  ports:
  - name: rcon
    port: {{ .Values.minecraftServer.rcon.port }}
    {{- if .Values.minecraftServer.rcon.nodePort }}
    nodePort: {{ .Values.minecraftServer.rcon.nodePort }}
    {{- end }}    
    targetPort: rcon
    protocol: TCP
  selector:
    {{- include "minecraft.selectorLabels" . | nindent 4 }}
{{- end }}
