name: Helm Chart CI
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  gofmt:
    name: Package Chart
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      
      - name: Run package
        uses: nolte/github-action/helm/build@master
      - name: Install (Ubuntu)
        if: matrix.config.os == 'ubuntu'
        run: echo ::set-env name=VERSION::"1.1.1"  
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          pattern: "dist/*.tgz"
          name: dist 
          
