name: Helm Chart CI
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  gofmt:
    name: Package Chart
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: Run tests
        uses: nolte/github-action/helm/testing@master      
      - name: Run package
        uses: nolte/github-action/helm/build@master
      - name: Define variables
        run: echo "Tags are > ${PUSH_TAG_VERSION}"
        env:
          VERSION: 1.1.1
      - name: Install (Ubuntu)
        run: echo ::set-env name=VERSION::"1.1.1"
        id: define_version
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          path: "dist/minecraft-${{ env.VERSION }}.tgz"
          name: minecraft-${{ env.VERSION }}.tgz
          
