name: Helm Chart CI
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  gofmt:
    name: Package Chart
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run tests
        uses: nolte/github-action/helm/testing@master      
      - name: Run package
        uses: nolte/github-action/helm/build@master
      - name: load chart facts
        uses: nolte/github-action/helm/set_facts@master
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          path: "dist/${{ env.CHARTNAME }}-${{ env.CHARTVERSION }}.tgz"
          name: ${{ env.CHARTNAME }}-${{ env.CHARTVERSION }}.tgz
      - name: Check out Chart Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: "nolte/helm-charts"     
          path: 'charts'
      - uses: actions/download-artifact@v1
        with:
          name: ${{ env.CHARTNAME }}-${{ env.CHARTVERSION }}.tgz
          path: 'charts/charts/'